export default {
    CREATE_TYPE_AREA_TYPE_REQUEST: "CREATE_TYPE_AREA_TYPE_REQUEST",
    CREATE_TYPE_AREA_TYPE_SUCCESS: "CREATE_TYPE_AREA_TYPE_SUCCESS",
    CREATE_TYPE_AREA_TYPE_FAIL: "CREATE_TYPE_AREA_TYPE_FAIL",

    GET_TYPE_AREA_TYPE_REQUEST: "GET_TYPE_AREA_TYPE_REQUEST",
    GET_TYPE_AREA_TYPE_SUCCESS: "GET_TYPE_AREA_TYPE_SUCCESS",
    GET_TYPE_AREA_TYPE_FAIL: "GET_TYPE_AREA_TYPE_FAIL",

    UPDATE_TYPE_AREA_TYPE_REQUEST: "UPDATE_TYPE_AREA_TYPE_REQUEST",
    UPDATE_TYPE_AREA_TYPE_SUCCESS: "UPDATE_TYPE_AREA_TYPE_SUCCESS",
    UPDATE_TYPE_AREA_TYPE_FAIL: "UPDATE_TYPE_AREA_TYPE_FAIL",

    DELETE_TYPE_AREA_TYPE_REQUEST: "DELETE_TYPE_AREA_TYPE_REQUEST",
    DELETE_TYPE_AREA_TYPE_SUCCESS: "DELETE_TYPE_AREA_TYPE_SUCCESS",
    DELETE_TYPE_AREA_TYPE_FAIL: "DELETE_TYPE_AREA_TYPE_FAIL",

    ACTIVATE_TYPE_AREA_TYPE_SUCCESS: "ACTIVATE_TYPE_AREA_TYPE_SUCCESS",
    DEACTIVATE_TYPE_AREA_TYPE_SUCCESS: "DEACTIVATE_TYPE_AREA_TYPE_SUCCESS",

    RESET_TYPE_AREA_TYPE: "RESET_TYPE_AREA_TYPE"
}