export default {
    CREATE_TRAININGS_REQUEST: "CREATE_TRAININGS_REQUEST",
    CREATE_TRAININGS_SUCCESS: "CREATE_TRAININGS_SUCCESS",
    CREATE_TRAININGS_FAIL: "CREATE_TRAININGS_FAIL",

    GET_TRAININGS_REQUEST: "GET_TRAININGS_REQUEST",
    GET_TRAININGS_SUCCESS: "GET_TRAININGS_SUCCESS",
    GET_TRAININGS_FAIL: "GET_TRAININGS_FAIL",

    DELETE_TRAININGS_REQUEST: "DELETE_TRAININGS_REQUEST",
    DELETE_TRAININGS_SUCCESS: "DELETE_TRAININGS_SUCCESS",
    DELETE_TRAININGS_FAIL: "DELETE_TRAININGS_FAIL",

    UPDATE_TRAININGS_REQUEST: "UPDATE_TRAININGS_REQUEST",
    UPDATE_TRAININGS_SUCCESS: "UPDATE_TRAININGS_SUCCESS",
    UPDATE_TRAININGS_FAIL: "UPDATE_TRAININGS_FAIL",

    TRAININGS_FETCH_REQUEST:"TRAININGS_FETCH_REQUEST",
    TRAININGS_FETCH_SUCCESS:"TRAININGS_FETCH_SUCCESS",
    TRAININGS_FETCH_FAIL:"TRAININGS_FETCH_FAIL",
    TRAININGS_RESET:"TRAININGS_RESET",
    TRAININGS_CREATE_SUCCESS: "TRAININGS_CREATE_SUCCESS",
    TRAININGS_DELETE_SUCCESS: "TRAININGS_DELETE_SUCCESS",
    TRAININGS_UPDATE_SUCCESS: "TRAININGS_UPDATE_SUCCESS",
    DOWNLOAD_FILE_REQUEST: "DOWNLOAD_FILE_REQUEST",
    DOWNLOAD_FILE_SUCCESS: "DOWNLOAD_FILE_SUCCESS",
    DOWNLOAD_FILE_FAIL: "DOWNLOAD_FILE_FAIL",

    UPLOAD_OBUKA_REQUEST: "UPLOAD_OBUKA_REQUEST",
    UPLOAD_OBUKA_SUCCESS: "UPLOAD_OBUKA_SUCCESS",
    UPLOAD_OBUKA_FAIL: "UPLOAD_OBUKA_FAIL",

    CHANGE_OUTPUT_OBUKA_PRINT_URL_SUCCESS: "CHANGE_OUTPUT_OBUKA_PRINT_URL_SUCCESS",
    CHANGE_OUTPUT_OBUKA_PRINT_URL_FAIL: "CHANGE_OUTPUT_OBUKA_PRINT_URL_FAIL",

    OBUKA_UPDATE_FOR_OUTPUT_DOCUMENT_PRINT_STATE_PATH: "OBUKA_UPDATE_FOR_OUTPUT_DOCUMENT_PRINT_STATE_PATH",

    CHANGE_OUTPUT_CERTIFICATE_PRINT_URL_SUCCESS: "CHANGE_OUTPUT_CERTIFICATE_PRINT_URL_SUCCESS",
    CHANGE_OUTPUT_CERTIFICATE_PRINT_URL_FAIL: "CHANGE_OUTPUT_CERTIFICATE_PRINT_URL_FAIL",

    CERTIFICATE_UPDATE_FOR_OUTPUT_DOCUMENT_PRINT_STATE_PATH: "CERTIFICATE_UPDATE_FOR_OUTPUT_DOCUMENT_PRINT_STATE_PATH",

    DOWNLOAD_OBUKA_REQUEST: "DOWNLOAD_OBUKA_REQUEST",
    DOWNLOAD_OBUKA_SUCCESS: "DOWNLOAD_OBUKA_SUCCESS",
    DOWNLOAD_OBUKA_FAIL: "DOWNLOAD_OBUKA_FAIL",

    DOWNLOAD_CERTIFICATE_REQUEST: "DOWNLOAD_CERTIFICATE_REQUEST",
    DOWNLOAD_CERTIFICATE_SUCCESS: "DOWNLOAD_CERTIFICATE_SUCCESS",
    DOWNLOAD_CERTIFICATE_FAIL: "DOWNLOAD_CERTIFICATE_FAIL",

    RESET_TRAININGS: "RESET_TRAININGS",
}