export default {
    CREATE_LANGUAGES_REQUEST: "CREATE_LANGUAGES_REQUEST",
    CREATE_LANGUAGES_SUCCESS: "CREATE_LANGUAGES_SUCCESS",
    CREATE_LANGUAGES_FAIL: "CREATE_LANGUAGES_FAIL",

    GET_LANGUAGES_REQUEST: "GET_LANGUAGES_REQUEST",
    GET_LANGUAGES_SUCCESS: "GET_LANGUAGES_SUCCESS",
    GET_LANGUAGES_FAIL: "GET_LANGUAGES_FAIL",

    DELETE_LANGUAGES_REQUEST: "DELETE_LANGUAGES_REQUEST",
    DELETE_LANGUAGES_SUCCESS: "DELETE_LANGUAGES_SUCCESS",
    DELETE_LANGUAGES_FAIL: "DELETE_LANGUAGES_FAIL",

    UPDATE_LANGUAGES_REQUEST: "UPDATE_LANGUAGES_REQUEST",
    UPDATE_LANGUAGES_SUCCESS: "UPDATE_LANGUAGES_SUCCESS",
    UPDATE_LANGUAGES_FAIL: "UPDATE_LANGUAGES_FAIL",

    RESET_LANGUAGES: "RESET_LANGUAGES",
}