export default {

    TEMPLATES_FETCH_BY_TYPE_REQUEST: "TEMPLATES_FETCH_BY_TYPE_REQUEST",
    TEMPLATES_FETCH_BY_TYPE_SUCCESS: "TEMPLATES_FETCH_BY_TYPE_SUCCESS",
    TEMPLATES_FETCH_BY_TYPE_FAIL: "TEMPLATES_FETCH_BY_TYPE_FAIL",

    TEMPLATES_GENERATE_REQUEST: "TEMPLATES_GENERATE_REQUEST",
    TEMPLATES_GENERATE_SUCCESS: "TEMPLATES_GENERATE_SUCCESS",
    TEMPLATES_GENERATE_FAIL: "TEMPLATES_GENERATE_FAIL",

    UPDATE_TEMPLATE_PATH: "UPDATE_TEMPLATE_PATH",

}