export default {
    CREATE_ROLE_POSITION_TYPE_REQUEST: "CREATE_ROLE_POSITION_TYPE_REQUEST",
    CREATE_ROLE_POSITION_TYPE_SUCCESS: "CREATE_ROLE_POSITION_TYPE_SUCCESS",
    CREATE_ROLE_POSITION_TYPE_FAIL: "CREATE_ROLE_POSITION_TYPE_FAIL",

    GET_ROLE_POSITION_TYPES_REQUEST: "GET_ROLE_POSITION_TYPES_REQUEST",
    GET_ROLE_POSITION_TYPES_SUCCESS: "GET_ROLE_POSITION_TYPES_SUCCESS",
    GET_ROLE_POSITION_TYPES_FAIL: "GET_ROLE_POSITION_TYPES_FAIL",

    UPDATE_ROLE_POSITION_TYPE_REQUEST: "UPDATE_ROLE_POSITION_TYPE_REQUEST",
    UPDATE_ROLE_POSITION_TYPE_SUCCESS: "UPDATE_ROLE_POSITION_TYPE_SUCCESS",
    UPDATE_ROLE_POSITION_TYPE_FAIL: "UPDATE_ROLE_POSITION_TYPE_FAIL",

    DELETE_ROLE_POSITION_TYPE_REQUEST: "DELETE_ROLE_POSITION_TYPE_REQUEST",
    DELETE_ROLE_POSITION_TYPE_SUCCESS: "DELETE_ROLE_POSITION_TYPE_SUCCESS",
    DELETE_ROLE_POSITION_TYPE_FAIL: "DELETE_ROLE_POSITION_TYPE_FAIL",

    ACTIVATE_ROLE_POSITION_TYPE_SUCCESS: "ACTIVATE_WORKE_ROLE_POSITION_TYPE_SUCCESS",
    DEACTIVATE_ROLE_POSITION_TYPE_SUCCESS: "DEACTIVATE_ROLE_POSITION_TYPE_SUCCESS",

    RESET_ROLE_POSITION_TYPES: "RESET_ROLE_POSITION_TYPES"
}