export default {
    CREATE_PRIVATE_HEALTHCARE_REQUEST: "CREATE_PRIVATE_HEALTHCARE_REQUEST",
    CREATE_PRIVATE_HEALTHCARE_SUCCESS: "CREATE_PRIVATE_HEALTHCARE_SUCCESS",
    CREATE_PRIVATE_HEALTHCARE_FAIL: "CREATE_PRIVATE_HEALTHCARE_FAIL",

    GET_PRIVATE_HEALTHCARES_REQUEST: "GET_PRIVATE_HEALTHCARES_REQUEST",
    GET_PRIVATE_HEALTHCARES_SUCCESS: "GET_PRIVATE_HEALTHCARES_SUCCESS",
    GET_PRIVATE_HEALTHCARES_FAIL: "GET_PRIVATE_HEALTHCARES_FAIL",

    DELETE_PRIVATE_HEALTHCARE_REQUEST: "DELETE_PRIVATE_HEALTHCARE_REQUEST",
    DELETE_PRIVATE_HEALTHCARE_SUCCESS: "DELETE_PRIVATE_HEALTHCARE_SUCCESS",
    DELETE_PRIVATE_HEALTHCARE_FAIL: "DELETE_PRIVATE_HEALTHCARE_FAIL",

    UPDATE_PRIVATE_HEALTHCARE_REQUEST: "UPDATE_PRIVATE_HEALTHCARE_REQUEST",
    UPDATE_PRIVATE_HEALTHCARE_SUCCESS: "UPDATE_PRIVATE_HEALTHCARE_SUCCESS",
    UPDATE_PRIVATE_HEALTHCARE_FAIL: "UPDATE_PRIVATE_HEALTHCARE_FAIL",

    ACTIVATE_PRIVATE_HEALTHCARE_SUCCESS: "ACTIVATE_PRIVATE_HEALTHCARE_SUCCESS",
    DEACTIVATE_PRIVATE_HEALTHCARE_SUCCESS: "DEACTIVATE_PRIVATE_HEALTHCARE_SUCCESS",

    CONTINUE_HEALTH_CARE_REQUEST: "CONTINUE_HEALTH_CARE_REQUEST",
    CONTINUE_HEALTH_CARE_SUCCESS: "CONTINUE_HEALTH_CARE_SUCCESS",
    CONTINUE_HEALTH_CARE_FAIL: "CONTINUE_HEALTH_CARE_FAIL",
    
    RESET_PRIVATE_HEALTHCARES: "RESET_PRIVATE_HEALTHCARES",

    EMPTY_LIST: "EMPTY_LIST",
}