export default {
    CREATE_UNIVERSITY_TYPE_REQUEST: "CREATE_UNIVERSITY_TYPE_REQUEST",
    CREATE_UNIVERSITY_TYPE_SUCCESS: "CREATE_UNIVERSITY_TYPE_SUCCESS",
    CREATE_UNIVERSITY_TYPE_FAIL: "CREATE_UNIVERSITY_TYPE_FAIL",

    GET_UNIVERSITY_TYPE_REQUEST: "GET_UNIVERSITY_TYPE_REQUEST",
    GET_UNIVERSITY_TYPE_SUCCESS: "GET_UNIVERSITY_TYPE_SUCCESS",
    GET_UNIVERSITY_TYPE_FAIL: "GET_UNIVERSITY_TYPE_FAIL",

    UPDATE_UNIVERSITY_TYPE_REQUEST: "UPDATE_UNIVERSITY_TYPE_REQUEST",
    UPDATE_UNIVERSITY_TYPE_SUCCESS: "UPDATE_UNIVERSITY_TYPE_SUCCESS",
    UPDATE_UNIVERSITY_TYPE_FAIL: "UPDATE_UNIVERSITY_TYPE_FAIL",

    DELETE_UNIVERSITY_TYPE_REQUEST: "DELETE_UNIVERSITY_TYPE_REQUEST",
    DELETE_UNIVERSITY_TYPE_SUCCESS: "DELETE_UNIVERSITY_TYPE_SUCCESS",
    DELETE_UNIVERSITY_TYPE_FAIL: "DELETE_UNIVERSITY_TYPE_FAIL",

    ACTIVATE_UNIVERSITY_TYPE_SUCCESS: "ACTIVATE_UNIVERSITY_TYPE_SUCCESS",
    DEACTIVATE_UNIVERSITY_TYPE_SUCCESS: "DEACTIVATE_UNIVERSITY_TYPE_SUCCESS",

    RESET_UNIVERSITY_TYPE: "RESET_UNIVERSITY_TYPE"
}