export default {

    USER_INFO_FETCH_REQUEST: "USER_INFO_FETCH_REQUEST",
    USER_INFO_FETCH_SUCCESS: "USER_INFO_FETCH_SUCCESS",
    USER_INFO_FETCH_FAIL: "USER_INFO_FETCH_FAIL",

    USER_INFO_RESET: "USER_INFO_RESET",

    LANGUAGE_VALUE_CHANGE: "LANGUAGE_VALUE_CHANGE",
    HEADER_TITLE_CHANGE: "HEADER_TITLE_CHANGE",
    HEADER_TITLE_RESET: "HEADER_TITLE_RESET",
    SET_ACTION: "SET_ACTION"
}