export default {
  CREATE_DOCUMENT_TYPE_REQUEST: "CREATE_DOCUMENT_TYPE_REQUEST",
  CREATE_DOCUMENT_TYPE_SUCCESS: "CREATE_DOCUMENT_TYPE_SUCCESS",
  CREATE_DOCUMENT_TYPE_FAIL: "CREATE_DOCUMENT_TYPE_FAIL",

  GET_DOCUMENT_TYPES_REQUEST: "GET_DOCUMENT_TYPES_REQUEST",
  GET_DOCUMENT_TYPES_SUCCESS: "GET_DOCUMENT_TYPES_SUCCESS",
  GET_DOCUMENT_TYPES_FAIL: "GET_DOCUMENT_TYPES_FAIL",

  DELETE_DOCUMENT_TYPE_REQUEST: "DELETE_DOCUMENT_TYPE_REQUEST",
  DELETE_DOCUMENT_TYPE_SUCCESS: "DELETE_DOCUMENT_TYPE_SUCCESS",
  DELETE_DOCUMENT_TYPE_FAIL: "DELETE_DOCUMENT_TYPE_FAIL",

  UPDATE_DOCUMENT_TYPE_REQUEST: "UPDATE_DOCUMENT_TYPE_REQUEST",
  UPDATE_DOCUMENT_TYPE_SUCCESS: "UPDATE_DOCUMENT_TYPE_SUCCESS",
  UPDATE_DOCUMENT_TYPE_FAIL: "UPDATE_DOCUMENT_TYPE_FAIL",

  ACTIVATE_DOCUMENT_TYPE_SUCCESS: "ACTIVATE_DOCUMENT_TYPE_SUCCESS",
  DEACTIVATE_DOCUMENT_TYPE_SUCCESS: "DEACTIVATE_DOCUMENT_TYPE_SUCCESS",

  RESET_DOCUMENT_TYPES: "RESET_DOCUMENT_TYPES",
};
