export default {
    GET_OUTPUT_DOCUMENTS_PRINT_REQUEST: "GET_OUTPUT_DOCUMENTS_PRINT_REQUEST",
    GET_OUTPUT_DOCUMENTS_PRINT_SUCCESS: "GET_OUTPUT_DOCUMENTS_PRINT_SUCCESS",
    GET_OUTPUT_DOCUMENTS_PRINT_FAIL: "GET_OUTPUT_DOCUMENTS_PRINT_FAIL",

    CREATE_OUTPUT_DOCUMENT_PRINT_REQUEST: "CREATE_OUTPUT_DOCUMENT_PRINT_REQUEST",
    CREATE_OUTPUT_DOCUMENT_PRINT_SUCCESS: "CREATE_OUTPUT_DOCUMENT_PRINT_SUCCESS",
    CREATE_OUTPUT_DOCUMENT_PRINT_FAIL: "CREATE_OUTPUT_DOCUMENT_PRINT_FAIL",

    DELETE_OUTPUT_DOCUMENT_PRINT_REQUEST: "DELETE_OUTPUT_DOCUMENT_PRINT_REQUEST",
    DELETE_OUTPUT_DOCUMENT_PRINT_SUCCESS: "DELETE_OUTPUT_DOCUMENT_PRINT_SUCCESS",
    DELETE_OUTPUT_DOCUMENT_PRINT_FAIL: "DELETE_OUTPUT_DOCUMENT_PRINT_FAIL",

    UPDATE_OUTPUT_DOCUMENT_PRINT_REQUEST: "UPDATE_OUTPUT_DOCUMENT_PRINT_REQUEST",
    UPDATE_OUTPUT_DOCUMENT_PRINT_SUCCESS: "UPDATE_OUTPUT_DOCUMENT_PRINT_SUCCESS",
    UPDATE_OUTPUT_DOCUMENT_PRINT_FAIL: "UPDATE_OUTPUT_DOCUMENT_PRINT_FAIL",

    GET_PARAMETERS_FOR_OUTPUT_DOCUMENT_PRINT_SQL_REQUEST: "GET_PARAMETERS_FOR_OUTPUT_DOCUMENT_PRINT_SQL_REQUEST",
    GET_PARAMETERS_FOR_OUTPUT_DOCUMENT_PRINT_SQL_SUCCESS: "GET_PARAMETERS_FOR_OUTPUT_DOCUMENT_PRINT_SQL_SUCCESS",
    GET_PARAMETERS_FOR_OUTPUT_DOCUMENT_PRINT_SQL_FAIL: "GET_PARAMETERS_FOR_OUTPUT_DOCUMENT_PRINT_SQL_FAIL",

    TEMPLATE_UPDATE_FOR_OUTPUT_DOCUMENT_PRINT_STATE_PATH: "TEMPLATE_UPDATE_FOR_OUTPUT_DOCUMENT_PRINT_STATE_PATH",
    CHANGE_OUTPUT_DOCUMENT_PRINT_URL_SUCCESS: "CHANGE_OUTPUT_DOCUMENT_PRINT_URL_SUCCESS",
    CHANGE_OUTPUT_DOCUMENT_PRINT_URL_FAIL: "CHANGE_OUTPUT_DOCUMENT_PRINT_URL_FAIL",

    GET_OUTPUT_DOCUMENT_PRINT_TYPE_REQUEST: 'GET_OUTPUT_DOCUMENT_PRINT_TYPE_REQUEST',
    GET_OUTPUT_DOCUMENT_PRINT_TYPE_SUCCESS: 'GET_OUTPUT_DOCUMENT_PRINT_TYPE_SUCCESS',
    GET_OUTPUT_DOCUMENT_PRINT_TYPE_FAIL: 'GET_OUTPUT_DOCUMENT_PRINT_TYPE_FAIL',

    RESET_OUTPUT_DOCUMENTS_PRINT: "RESET_OUTPUT_DOCUMENTS_PRINT",
};
