export default {
  CREATE_DOCUMENT_REQUEST: "CREATE_DOCUMENT_REQUEST",
  CREATE_DOCUMENT_SUCCESS: "CREATE_DOCUMENT_SUCCESS",
  CREATE_DOCUMENT_FAIL: "CREATE_DOCUMENT_FAIL",

  GET_DOCUMENTS_REQUEST: "GET_DOCUMENTS_REQUEST",
  GET_DOCUMENTS_SUCCESS: "GET_DOCUMENTS_SUCCESS",
  GET_DOCUMENTS_FAIL: "GET_DOCUMENTS_FAIL",

  GET_DOCUMENTS_BY_DOSIE_REQUEST: "GET_DOCUMENTS_BY_DOSIE_REQUEST",
  GET_DOCUMENTS_BY_DOSIE_SUCCESS: "GET_DOCUMENTS_BY_DOSIE_SUCCESS",
  GET_DOCUMENTS_BY_DOSIE_FAIL: "GET_DOCUMENTS_BY_DOSIE_FAIL",

  DELETE_DOCUMENTS_REQUEST: "DELETE_DOCUMENTS_REQUEST",
  DELETE_DOCUMENTS_SUCCESS: "DELETE_DOCUMENTS_SUCCESS",
  DELETE_DOCUMENTS_FAIL: "DELETE_DOCUMENTS_FAIL",

  UPDATE_DOCUMENT_REQUEST: "UPDATE_DOCUMENT_REQUEST",
  UPDATE_DOCUMENT_SUCCESS: "UPDATE_DOCUMENT_SUCCESS",
  UPDATE_DOCUMENT_FAIL: "UPDATE_DOCUMENT_FAIL",

  UPLOAD_DOCUMENT_REQUEST: "UPLOAD_DOCUMENT_REQUEST",
  UPLOAD_DOCUMENT_SUCCESS: "UPLOAD_DOCUMENT_SUCCESS",
  UPLOAD_DOCUMENT_FAIL: "UPLOAD_DOCUMENT_FAIL",

  DOWNLOAD_DOCUMENT_REQUEST: "DOWNLOAD_DOCUMENT_REQUEST",
  DOWNLOAD_DOCUMENT_SUCCESS: "DOWNLOAD_DOCUMENT_SUCCESS",
  DOWNLOAD_DOCUMENT_FAIL: "DOWNLOAD_DOCUMENT_FAIL",

  DOCUMENT_UPDATE_STATE_URL: "DOCUMENT_UPDATE_STATE_URL",
  CHANGE_DOC_URL_SUCCESS: "CHANGE_DOC_URL_SUCCESS",
  CHANGE_DOC_URL_FAIL: "CHANGE_DOC_URL_FAIL",

  RESET_DOCUMENTS: "RESET_DOCUMENTS",
};
