export default {
  GET_ALL_DOSIE_REQUEST: "GET_ALL_DOSIE_REQUEST",
  GET_ALL_DOSIE_SUCCESS: "GET_ALL_DOSIE_SUCCESS",
  GET_ALL_DOSIE_FAIL: "GET_ALL_DOSIE_FAIL",

  GET_DOSIE_BY_USER_REQUEST: "GET_DOSIE_BY_USER_REQUEST",
  GET_DOSIE_BY_USER_SUCCESS: "GET_DOSIE_BY_USER_SUCCESS",
  GET_DOSIE_BY_USER_FAIL: "GET_DOSIE_BY_USER_FAIL",

  CREATE_DOSIE_REQUEST: "CREATE_DOSIE_REQUEST",
  CREATE_DOSIE_SUCCESS: "CREATE_DOSIE_SUCCESS",
  CREATE_DOSIE_FAIL: "CREATE_DOSIE_FAIL",

  UPDATE_DOSIE_REQUEST: "UPDATE_DOSIE_REQUEST",
  UPDATE_DOSIE_SUCCESS: "UPDATE_DOSIE_SUCCESS",
  UPDATE_DOSIE_FAIL: "UPADTE_DOSIE_FAIL",

  DELETE_DOSIE_REQUEST: "DELETE_DOSIE_REQUEST",
  DELETE_DOSIE_SUCCESS: "DELETE_DOSIE_SUCCESS",
  DELETE_DOSIE_FAIL: "DELETE_DOSIE_FAIL",

  GET_FILTERED_USERS_REQUEST: "GET_FILTERED_USERS_REQUEST",
  GET_FILTERED_USERS_SUCCESS: "GET_FILTERED_USERS_SUCCESS",
  GET_FILTERED_USERS_FAIL: "GET_FILTERED_USERS_FAIL",

  GET_ALL_REQUESTS_REQUEST: "GET_ALL_REQUESTS_REQUEST",
  GET_ALL_REQUESTS_SUCCESS: "GET_ALL_REQUESTS_SUCCESS",
  GET_ALL_REQUESTS_FAIL: "GET_ALL_REQUESTS_FAIL",

  GET_VACATION_DAYS_REQUEST: "GET_VACATION_DAYS_REQUEST",
  GET_VACATION_DAYS_SUCCESS: "GET_VACATION_DAYS_SUCCESS",
  GET_VACATION_DAYS_FAIL: "GET_VACATION_DAYS_FAIL",

  RESET_DOSIE: "RESET_DOSIE",
};
