export default {
    CREATE_ROLES_POSITION_REQUEST: "CREATE_ROLES_POSITION_REQUEST",
    CREATE_ROLES_POSITION_SUCCESS: "CREATE_ROLES_POSITION_SUCCESS",
    CREATE_ROLES_POSITION_FAIL: "CREATE_ROLES_POSITION_FAIL",

    GET_ROLES_POSITIONS_REQUEST: "GET_ROLES_POSITIONS_REQUEST",
    GET_ROLES_POSITIONS_SUCCESS: "GET_ROLES_POSITIONS_SUCCESS",
    GET_ROLES_POSITIONS_FAIL: "GET_ROLES_POSITIONS_FAIL",

    DELETE_ROLES_POSITION_REQUEST: "DELETE_ROLES_POSITION_REQUEST",
    DELETE_ROLES_POSITION_SUCCESS: "DELETE_ROLES_POSITION_SUCCESS",
    DELETE_ROLES_POSITION_FAIL: "DELETE_ROLES_POSITION_FAIL",

    UPDATE_ROLES_POSITION_REQUEST: "UPDATE_ROLES_POSITION_REQUEST",
    UPDATE_ROLES_POSITION_SUCCESS: "UPDATE_ROLES_POSITION_SUCCESS",
    UPDATE_ROLES_POSITION_FAIL: "UPDATE_ROLES_POSITION_FAIL",

    ACTIVATE_ROLES_POSITION_SUCCESS: "ACTIVATE_ROLES_POSITION_SUCCESS",
    DEACTIVATE_ROLES_POSITION_SUCCESS: "DEACTIVATE_ROLES_POSITION_SUCCESS",

    RESET_ROLES_POSITIONS: "RESET_ROLES_POSITIONS",

    EMPTY_LIST: "EMPTY_LIST",
}