export default {
    CREATE_DEGREE_EDUCATION_TYPE_REQUEST: "CREATE_DEGREE_EDUCATION_TYPE_REQUEST",
    CREATE_DEGREE_EDUCATION_TYPE_SUCCESS: "CREATE_DEGREE_EDUCATION_TYPE_SUCCESS",
    CREATE_DEGREE_EDUCATION_TYPE_FAIL: "CREATE_DEGREE_EDUCATION_TYPE_FAIL",

    GET_DEGREE_EDUCATION_TYPE_REQUEST: "GET_DEGREE_EDUCATION_TYPE_REQUEST",
    GET_DEGREE_EDUCATION_TYPE_SUCCESS: "GET_DEGREE_EDUCATION_TYPE_SUCCESS",
    GET_DEGREE_EDUCATION_TYPE_FAIL: "GET_DEGREE_EDUCATION_TYPE_FAIL",

    UPDATE_DEGREE_EDUCATION_TYPE_REQUEST: "UPDATE_DEGREE_EDUCATION_TYPE_REQUEST",
    UPDATE_DEGREE_EDUCATION_TYPE_SUCCESS: "UPDATE_DEGREE_EDUCATION_TYPE_SUCCESS",
    UPDATE_DEGREE_EDUCATION_TYPE_FAIL: "UPDATE_DEGREE_EDUCATION_TYPE_FAIL",

    DELETE_DEGREE_EDUCATION_TYPE_REQUEST: "DELETE_DEGREE_EDUCATION_TYPE_REQUEST",
    DELETE_DEGREE_EDUCATION_TYPE_SUCCESS: "DELETE_DEGREE_EDUCATION_TYPE_SUCCESS",
    DELETE_DEGREE_EDUCATION_TYPE_FAIL: "DELETE_DEGREE_EDUCATION_TYPE_FAIL",

    ACTIVATE_DEGREE_EDUCATION_TYPE_SUCCESS: "ACTIVATE_DEGREE_EDUCATION_TYPE_SUCCESS",
    DEACTIVATE_DEGREE_EDUCATION_TYPE_SUCCESS: "DEACTIVATE_DEGREE_EDUCATION_TYPE_SUCCESS",

    RESET_DEGREE_EDUCATION_TYPE: "RESET_DEGREE_EDUCATION_TYPE"
}