export default {
    CREATE_FACULTY_TYPE_REQUEST: "CREATE_FACULTY_TYPE_REQUEST",
    CREATE_FACULTY_TYPE_SUCCESS: "CREATE_FACULTY_TYPE_SUCCESS",
    CREATE_FACULTY_TYPE_FAIL: "CREATE_FACULTY_TYPE_FAIL",

    GET_FACULTY_TYPE_REQUEST: "GET_FACULTY_TYPE_REQUEST",
    GET_FACULTY_TYPE_SUCCESS: "GET_FACULTY_TYPE_SUCCESS",
    GET_FACULTY_TYPE_FAIL: "GET_FACULTY_TYPE_FAIL",

    UPDATE_FACULTY_TYPE_REQUEST: "UPDATE_FACULTY_TYPE_REQUEST",
    UPDATE_FACULTY_TYPE_SUCCESS: "UPDATE_FACULTY_TYPE_SUCCESS",
    UPDATE_FACULTY_TYPE_FAIL: "UPDATE_FACULTY_TYPE_FAIL",

    DELETE_FACULTY_TYPE_REQUEST: "DELETE_FACULTY_TYPE_REQUEST",
    DELETE_FACULTY_TYPE_SUCCESS: "DELETE_FACULTY_TYPE_SUCCESS",
    DELETE_FACULTY_TYPE_FAIL: "DELETE_FACULTY_TYPE_FAIL",

    ACTIVATE_FACULTY_TYPE_SUCCESS: "ACTIVATE_FACULTY_TYPE_SUCCESS",
    DEACTIVATE_FACULTY_TYPE_SUCCESS: "DEACTIVATE_FACULTY_TYPE_SUCCESS",

    RESET_FACULTY_TYPE: "RESET_FACULTY_TYPE"
}