export default {
    CREATE_COUNTRY_TYPE_REQUEST: "CREATE_COUNTRY_TYPE_REQUEST",
    CREATE_COUNTRY_TYPE_SUCCESS: "CREATE_COUNTRY_TYPE_SUCCESS",
    CREATE_COUNTRY_TYPE_FAIL: "CREATE_COUNTRY_TYPE_FAIL",

    GET_COUNTRY_TYPE_REQUEST: "GET_COUNTRY_TYPE_REQUEST",
    GET_COUNTRY_TYPE_SUCCESS: "GET_COUNTRY_TYPE_SUCCESS",
    GET_COUNTRY_TYPE_FAIL: "GET_COUNTRY_TYPE_FAIL",

    UPDATE_COUNTRY_TYPE_REQUEST: "UPDATE_COUNTRY_TYPE_REQUEST",
    UPDATE_COUNTRY_TYPE_SUCCESS: "UPDATE_COUNTRY_TYPE_SUCCESS",
    UPDATE_COUNTRY_TYPE_FAIL: "UPDATE_COUNTRY_TYPE_FAIL",

    DELETE_COUNTRY_TYPE_REQUEST: "DELETE_COUNTRY_TYPE_REQUEST",
    DELETE_COUNTRY_TYPE_SUCCESS: "DELETE_COUNTRY_TYPE_SUCCESS",
    DELETE_COUNTRY_TYPE_FAIL: "DELETE_COUNTRY_TYPE_FAIL",

    ACTIVATE_COUNTRY_TYPE_SUCCESS: "ACTIVATE_COUNTRY_TYPE_SUCCESS",
    DEACTIVATE_COUNTRY_TYPE_SUCCESS: "DEACTIVATE_COUNTRY_TYPE_SUCCESS",

    RESET_COUNTRY_TYPE: "RESET_COUNTRY_TYPE"
}