export default {
    CREATE_PROJECTS_REQUEST: "CREATE_PROJECTS_REQUEST",
    CREATE_PROJECTS_SUCCESS: "CREATE_PROJECTS_SUCCESS",
    CREATE_PROJECTS_FAIL: "CREATE_PROJECTS_FAIL",

    GET_PROJECTS_REQUEST: "GET_PROJECTS_REQUEST",
    GET_PROJECTS_SUCCESS: "GET_PROJECTS_SUCCESS",
    GET_PROJECTS_FAIL: "GET_PROJECTS_FAIL",

    DELETE_PROJECTS_REQUEST: "DELETE_PROJECTS_REQUEST",
    DELETE_PROJECTS_SUCCESS: "DELETE_PROJECTS_SUCCESS",
    DELETE_PROJECTS_FAIL: "DELETE_PROJECTS_FAIL",

    UPDATE_PROJECTS_REQUEST: "UPDATE_PROJECTS_REQUEST",
    UPDATE_PROJECTS_SUCCESS: "UPDATE_PROJECTS_SUCCESS",
    UPDATE_PROJECTS_FAIL: "UPDATE_PROJECTS_FAIL",

    RESET_PROJECTS: "RESET_PROJECTS",
}