export default {
    CREATE_EDUCATION_REQUEST: "CREATE_EDUCATION_REQUEST",
    CREATE_EDUCATION_SUCCESS: "CREATE_EDUCATION_SUCCESS",
    CREATE_EDUCATION_FAIL: "CREATE_EDUCATION_FAIL",

    GET_EDUCATION_REQUEST: "GET_EDUCATION_REQUEST",
    GET_EDUCATION_SUCCESS: "GET_EDUCATION_SUCCESS",
    GET_EDUCATION_FAIL: "GET_EDUCATION_FAIL",

    DELETE_EDUCATION_REQUEST: "DELETE_EDUCATION_REQUEST",
    DELETE_EDUCATION_SUCCESS: "DELETE_EDUCATION_SUCCESS",
    DELETE_EDUCATION_FAIL: "DELETE_EDUCATION_FAIL",

    UPDATE_EDUCATION_REQUEST: "UPDATE_EDUCATION_REQUEST",
    UPDATE_EDUCATION_SUCCESS: "UPDATE_EDUCATION_SUCCESS",
    UPDATE_EDUCATION_FAIL: "UPDATE_EDUCATION_FAIL",

    UPLOAD_DIPLOMA_REQUEST: "UPLOAD_DIPLOMA_REQUEST",
    UPLOAD_DIPLOMA_SUCCESS: "UPLOAD_DIPLOMA_SUCCESS",
    UPLOAD_DIPLOMA_FAIL: "UPLOAD_DIPLOMA_FAIL",

    UPLOAD_UVERENIE_REQUEST: "UPLOAD_UVERENIE_REQUEST",
    UPLOAD_UVERENIE_SUCCESS: "UPLOAD_UVERENIE_SUCCESS",
    UPLOAD_UVERENIE_FAIL: "UPLOAD_UVERENIE_FAIL",

    DOWNLOAD_DIPLOMA_REQUEST: "DOWNLOAD_DIPLOMA_REQUEST",
    DOWNLOAD_DIPLOMA_SUCCESS: "DOWNLOAD_DIPLOMA_SUCCESS",
    DOWNLOAD_DIPLOMA_FAIL: "DOWNLOAD_DIPLOMA_FAIL",

    DOWNLOAD_UVERENIE_REQUEST: "DOWNLOAD_UVERENIE_REQUEST",
    DOWNLOAD_UVERENIE_SUCCESS: "DOWNLOAD_UVERENIE_SUCCESS",
    DOWNLOAD_UVERENIE_FAIL: "DOWNLOAD_UVERENIE_FAIL",

    RESET_EDUCATIONS: "RESET_EDUCATION",
}