export default {
    CREATE_WORKING_POSITION_REQUEST: "CREATE_WORKING_POSITION_REQUEST",
    CREATE_WORKING_POSITION_SUCCESS: "CREATE_WORKING_POSITION_SUCCESS",
    CREATE_WORKING_POSITION_FAIL: "CREATE_WORKING_POSITION_FAIL",

    GET_WORKING_POSITIONS_REQUEST: "GET_WORKING_POSITIONS_REQUEST",
    GET_WORKING_POSITIONS_SUCCESS: "GET_WORKING_POSITIONS_SUCCESS",
    GET_WORKING_POSITIONS_FAIL: "GET_WORKING_POSITIONS_FAIL",

    DELETE_WORKING_POSITION_REQUEST: "DELETE_WORKING_POSITION_REQUEST",
    DELETE_WORKING_POSITION_SUCCESS: "DELETE_WORKING_POSITION_SUCCESS",
    DELETE_WORKING_POSITION_FAIL: "DELETE_WORKING_POSITION_FAIL",

    UPDATE_WORKING_POSITION_REQUEST: "UPDATE_WORKING_POSITION_REQUEST",
    UPDATE_WORKING_POSITION_SUCCESS: "UPDATE_WORKING_POSITION_SUCCESS",
    UPDATE_WORKING_POSITION_FAIL: "UPDATE_WORKING_POSITION_FAIL",

    ACTIVATE_WORKING_POSITION_SUCCESS: "ACTIVATE_WORKING_POSITION_SUCCESS",
    DEACTIVATE_WORKING_POSITION_SUCCESS: "DEACTIVATE_WORKING_POSITION_SUCCESS",

    RESET_WORKING_POSITIONS: "RESET_WORKING_POSITIONS",

    EMPTY_LIST: "EMPTY_LIST",
}