export default {
    CREATE_WORKING_POSITION_TYPE_REQUEST: "CREATE_WORKING_POSITION_TYPE_REQUEST",
    CREATE_WORKING_POSITION_TYPE_SUCCESS: "CREATE_WORKING_POSITION_TYPE_SUCCESS",
    CREATE_WORKING_POSITION_TYPE_FAIL: "CREATE_WORKING_POSITION_TYPE_FAIL",

    GET_WORKING_POSITION_TYPES_REQUEST: "GET_WORKING_POSITION_TYPES_REQUEST",
    GET_WORKING_POSITION_TYPES_SUCCESS: "GET_WORKING_POSITION_TYPES_SUCCESS",
    GET_WORKING_POSITION_TYPES_FAIL: "GET_WORKING_POSITION_TYPES_FAIL",

    DELETE_WORKING_POSITION_TYPE_REQUEST: "DELETE_WORKING_POSITION_TYPE_REQUEST",
    DELETE_WORKING_POSITION_TYPE_SUCCESS: "DELETE_WORKING_POSITION_TYPE_SUCCESS",
    DELETE_WORKING_POSITION_TYPE_FAIL: "DELETE_WORKING_POSITION_TYPE_FAIL",

    UPDATE_WORKING_POSITION_TYPE_REQUEST: "UPDATE_WORKING_POSITION_TYPE_REQUEST",
    UPDATE_WORKING_POSITION_TYPE_SUCCESS: "UPDATE_WORKING_POSITION_TYPE_SUCCESS",
    UPDATE_WORKING_POSITION_TYPE_FAIL: "UPDATE_WORKING_POSITION_TYPE_FAIL",

    ACTIVATE_WORKING_POSITION_TYPE_SUCCESS: "ACTIVATE_WORKING_POSITION_TYPE_SUCCESS",
    DEACTIVATE_WORKING_POSITION_TYPE_SUCCESS: "DEACTIVATE_WORKING_POSITION_TYPE_SUCCESS",

    RESET_WORKING_POSITION_TYPES: "RESET_WORKING_POSITION_TYPES"
}